# -*- coding: utf-8 -*-
"""DevScope AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1juySyc_-TPKOzcanuikK6w_O3Mvfn7w8
"""

# ============================================
# INSTALL REQUIREMENTS
# ============================================

!pip install -q gradio requests pandas plotly

import requests
from datetime import datetime

GITHUB_API = "https://api.github.com/users"


class GitHubAnalyzer:

    # =========================
    # PROFILE
    # =========================

    def get_profile(self, username):

        response = requests.get(
            f"{GITHUB_API}/{username}"
        )

        if response.status_code != 200:
            return None

        return response.json()

    # =========================
    # REPOSITORIES
    # =========================

    def get_repositories(self, username):

        response = requests.get(
            f"{GITHUB_API}/{username}/repos?per_page=100"
        )

        if response.status_code != 200:
            return []

        return response.json()

    # =========================
    # LANGUAGES
    # =========================

    def analyze_languages(self, repos):

        languages = {}

        for repo in repos:

            lang = repo.get("language")

            if lang:

                languages[lang] = (
                    languages.get(lang, 0) + 1
                )

        return languages

    # =========================
    # STARS
    # =========================

    def total_stars(self, repos):

        return sum(
            repo.get(
                "stargazers_count",
                0
            )
            for repo in repos
        )

    # =========================
    # FORKS
    # =========================

    def total_forks(self, repos):

        return sum(
            repo.get(
                "forks_count",
                0
            )
            for repo in repos
        )

    # =========================
    # ACCOUNT AGE
    # =========================

    def account_age(self, profile):

        created = profile.get(
            "created_at"
        )

        if not created:
            return 0

        created = datetime.strptime(
            created,
            "%Y-%m-%dT%H:%M:%SZ"
        )

        return (
            datetime.now() - created
        ).days // 365

    # =========================
    # MOST STARRED REPO
    # =========================

    def most_starred_repo(self, repos):

        if not repos:
            return None

        return max(
            repos,
            key=lambda x:
            x.get(
                "stargazers_count",
                0
            )
        )

    # =========================
    # REPOSITORY SCORE
    # =========================

    def repository_score(
        self,
        repo_count
    ):

        if repo_count >= 20:
            return 20

        elif repo_count >= 10:
            return 15

        elif repo_count >= 5:
            return 10

        return 5

    # =========================
    # STAR SCORE
    # =========================

    def star_score(
        self,
        stars
    ):

        if stars >= 100:
            return 10

        elif stars >= 25:
            return 7

        elif stars >= 5:
            return 4

        return 1

    # =========================
    # FOLLOWER SCORE
    # =========================

    def follower_score(
        self,
        followers
    ):

        if followers >= 500:
            return 10

        elif followers >= 100:
            return 8

        elif followers >= 25:
            return 6

        elif followers >= 5:
            return 3

        return 1

    # =========================
    # LANGUAGE SCORE
    # =========================

    def language_score(
        self,
        languages
    ):

        count = len(languages)

        if count >= 5:
            return 10

        elif count >= 3:
            return 7

        return 4

    # =========================
    # README SCORE
    # =========================

    def readme_presence_score(
        self,
        repos
    ):

        if not repos:
            return 0

        score = 0

        checked = min(
            len(repos),
            20
        )

        for repo in repos[:20]:

            if repo.get(
                "description"
            ):
                score += 1

        percentage = (
            score / checked
        ) * 100

        if percentage >= 80:
            return 15

        elif percentage >= 50:
            return 10

        return 5

    # =========================
    # DOCUMENTATION QUALITY
    # =========================

    def documentation_quality_score(
        self,
        repos
    ):

        if not repos:
            return 0

        score = 0

        checked = min(
            len(repos),
            20
        )

        for repo in repos[:20]:

            repo_score = 0

            if repo.get(
                "description"
            ):
                repo_score += 1

            if repo.get(
                "homepage"
            ):
                repo_score += 1

            score += repo_score

        percentage = (
            score /
            (checked * 2)
        ) * 100

        if percentage >= 80:
            return 15

        elif percentage >= 50:
            return 10

        return 5

    # =========================
    # DIVERSITY SCORE
    # =========================

    def diversity_score(
        self,
        repos
    ):

        categories = {
            "ai": 0,
            "web": 0,
            "data": 0,
            "api": 0,
            "automation": 0
        }

        for repo in repos:

            name = repo.get(
                "name",
                ""
            ).lower()

            if "ai" in name:
                categories["ai"] += 1

            if "web" in name:
                categories["web"] += 1

            if "data" in name:
                categories["data"] += 1

            if "api" in name:
                categories["api"] += 1

            if "bot" in name:
                categories["automation"] += 1

        count = sum(
            1
            for v in categories.values()
            if v > 0
        )

        if count >= 3:
            return 10

        return 4

    # =========================
    # ACTIVITY SCORE
    # =========================

    def activity_score(
        self,
        repos
    ):

        if not repos:
            return 0

        latest = max(
            repos,
            key=lambda x:
            x.get(
                "updated_at",
                ""
            )
        )

        updated = datetime.strptime(
            latest["updated_at"],
            "%Y-%m-%dT%H:%M:%SZ"
        )

        days = (
            datetime.now() - updated
        ).days

        if days <= 30:
            return 10

        elif days <= 90:
            return 8

        elif days <= 180:
            return 5

        return 2

    # =========================
    # FINAL SCORE
    # =========================

    def portfolio_score(
        self,
        profile,
        repos
    ):

        languages = self.analyze_languages(
            repos
        )

        score = 0

        score += self.repository_score(
            len(repos)
        )

        score += self.star_score(
            self.total_stars(repos)
        )

        score += self.follower_score(
            profile.get(
                "followers",
                0
            )
        )

        score += self.language_score(
            languages
        )

        score += self.readme_presence_score(
            repos
        )

        score += self.documentation_quality_score(
            repos
        )

        score += self.diversity_score(
            repos
        )

        score += self.activity_score(
            repos
        )

        return min(
            score,
            100
        )


# =========================
# INITIALIZE
# =========================

analyzer = GitHubAnalyzer()


# =========================
# GRADE
# =========================

def calculate_grade(score):

    if score >= 90:
        return "A+"
    elif score >= 80:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"

    return "F"


# =========================
# REPORT GENERATOR
# =========================

def generate_report(username):

    profile = analyzer.get_profile(
        username
    )

    if profile is None:

        return {
            "error":
            "GitHub user not found"
        }

    repos = analyzer.get_repositories(
        username
    )

    score = analyzer.portfolio_score(
        profile,
        repos
    )

    return {

        "username":
        username,

        "name":
        profile.get(
            "name",
            "N/A"
        ),

        "followers":
        profile.get(
            "followers",
            0
        ),

        "following":
        profile.get(
            "following",
            0
        ),

        "repositories":
        len(repos),

        "stars":
        analyzer.total_stars(
            repos
        ),

        "forks":
        analyzer.total_forks(
            repos
        ),

        "languages":
        analyzer.analyze_languages(
            repos
        ),

        "score":
        score,

        "grade":
        calculate_grade(
            score
        )
    }


print("✅ DevScope AI Backend Ready")

import pandas as pd
import plotly.express as px


# ============================================
# LANGUAGE PIE CHART
# ============================================

def create_language_chart(report):

    languages = report["languages"]

    if not languages:

        return None

    df = pd.DataFrame({

        "Language": list(languages.keys()),
        "Count": list(languages.values())

    })

    fig = px.pie(
        df,
        names="Language",
        values="Count",
        title="Programming Languages Distribution",
        hole=0.45
    )

    fig.update_layout(
        height=500
    )

    return fig


# ============================================
# TOP REPOSITORIES CHART
# ============================================

def create_repo_chart(username):

    repos = analyzer.get_repositories(
        username
    )

    if not repos:

        return None

    repo_data = []

    for repo in repos:

        repo_data.append({

            "Repository":
            repo["name"],

            "Stars":
            repo["stargazers_count"]

        })

    df = pd.DataFrame(
        repo_data
    )

    df = df.sort_values(
        by="Stars",
        ascending=False
    ).head(10)

    fig = px.bar(

        df,

        x="Stars",

        y="Repository",

        orientation="h",

        title="Top Repositories by Stars"

    )

    fig.update_layout(
        height=500
    )

    return fig


# ============================================
# DASHBOARD METRICS
# ============================================

def generate_dashboard_data(username):

    report = generate_report(
        username
    )

    if "error" in report:

        return None

    metrics = {

        "Score":
        report["score"],

        "Grade":
        report["grade"],

        "Repositories":
        report["repositories"],

        "Followers":
        report["followers"],

        "Stars":
        report["stars"],

        "Forks":
        report["forks"]

    }

    return metrics


# ============================================
# COMPLETE ANALYTICS
# ============================================

def generate_analytics(username):

    report = generate_report(
        username
    )

    if "error" in report:

        return None

    language_chart = create_language_chart(
        report
    )

    repo_chart = create_repo_chart(
        username
    )

    metrics = generate_dashboard_data(
        username
    )

    return {

        "report":
        report,

        "metrics":
        metrics,

        "language_chart":
        language_chart,

        "repo_chart":
        repo_chart

    }

import gradio as gr

# ============================================
# MAIN ANALYSIS FUNCTION
# ============================================

def analyze_github(username):

    try:

        analytics = generate_analytics(
            username
        )

        if analytics is None:

            return (
                "❌ User not found",
                "",
                None,
                None
            )

        report = analytics["report"]
        metrics = analytics["metrics"]

        summary = f"""
# 👤 {report['name']}

### GitHub Username
{report['username']}

### Portfolio Score
**{report['score']}/100**

### Grade
**{report['grade']}**

---

### 📊 Statistics

- Repositories: {report['repositories']}
- Followers: {report['followers']}
- Following: {report['following']}
- Total Stars: {report['stars']}
- Total Forks: {report['forks']}

---

### 🧠 Languages

{', '.join(report['languages'].keys())}
"""

        cards = f"""
## 📈 Portfolio Metrics

🏆 Score: **{metrics['Score']}**

🎓 Grade: **{metrics['Grade']}**

📁 Repositories: **{metrics['Repositories']}**

⭐ Stars: **{metrics['Stars']}**

👥 Followers: **{metrics['Followers']}**

🍴 Forks: **{metrics['Forks']}**
"""

        return (
            summary,
            cards,
            analytics["language_chart"],
            analytics["repo_chart"]
        )

    except Exception as e:

        return (
            f"❌ Error: {str(e)}",
            "",
            None,
            None
        )


# ============================================
# CUSTOM CSS
# ============================================

custom_css = """

.gradio-container {
    background: linear-gradient(
        135deg,
        #0f172a,
        #111827,
        #1e293b
    );
}

h1 {
    text-align:center;
}

.metric-card {
    border-radius:20px;
}

footer {
    visibility:hidden;
}

"""


# ============================================
# UI
# ============================================

with gr.Blocks(
    theme=gr.themes.Soft(),
    css=custom_css,
    title="DevScope AI"
) as demo:

    gr.Markdown("""
    <div style="
    text-align:center;
    padding:40px;
    border-radius:25px;
    background:rgba(255,255,255,0.05);
    backdrop-filter:blur(12px);
    ">

    <h1 style="
    font-size:58px;
    margin-bottom:10px;
    ">
    🔍 DevScope AI
    </h1>

    <h3 style="
    margin-top:0;
    ">
    AI-Powered GitHub Portfolio Intelligence Platform
    </h3>

    <p style="
    font-size:18px;
    max-width:800px;
    margin:auto;
    ">
    Analyze repositories, stars, followers,
    activity, languages, documentation quality
    and portfolio strength like a recruiter.
    </p>

    </div>
    """)

    with gr.Row():

        username = gr.Textbox(
            label="GitHub Username",
            placeholder="Enter username..."
        )

        analyze_btn = gr.Button(
            "Analyze Portfolio",
            variant="primary"
        )

    with gr.Row():

        profile_output = gr.Markdown()

        metrics_output = gr.Markdown()

    with gr.Row():

        language_chart = gr.Plot(
            label="Languages"
        )

        repo_chart = gr.Plot(
            label="Top Repositories"
        )

    analyze_btn.click(
        fn=analyze_github,
        inputs=username,
        outputs=[
            profile_output,
            metrics_output,
            language_chart,
            repo_chart
        ]
    )

demo.launch(
    share=True,
    debug=True
)